

import Jama.Matrix;

import javax.swing.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * PR_GUI.java
 *
 * Created on 2015-03-05, 19:40:56
 */

/**
 * @author krzy
 */
public class PR_GUI extends javax.swing.JFrame {
    private Data data = new Data();
    private Classifier classifier;
    private Selection selection = new Selection();

    /**
     * Creates new form PR_GUI
     */
    private PR_GUI() {
        initComponents();
        setSize(720, 410);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReadDatasetButton = new javax.swing.JButton();
        ParseDatasetButton = new javax.swing.JButton();
        InfoPanel = new javax.swing.JPanel();
        InfoLabel = new javax.swing.JLabel();
        DatasetNameLabel = new javax.swing.JLabel();
        ValueDatasetNameLabel = new javax.swing.JLabel();
        ClassesLabel = new javax.swing.JLabel();
        FeaturesLabel = new javax.swing.JLabel();
        ValueFeaturesLabel = new javax.swing.JLabel();
        FeatureSpacePanel = new javax.swing.JPanel();
        FeatureLabel = new javax.swing.JLabel();
        FSDimensionLabel = new javax.swing.JLabel();
        FSDimensionComboBox = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        CriterionLabel = new javax.swing.JLabel();
        FeatureSelectionRadioButton = new javax.swing.JRadioButton();
        FisherCriterionComboBox = new javax.swing.JComboBox();
        FeatureExtarctionRadioButton = new javax.swing.JRadioButton();
        PCALDAComboBox = new javax.swing.JComboBox();
        EnergyLabel = new javax.swing.JLabel();
        PCAEnergyTextField = new javax.swing.JTextField();
        Percent2Label = new javax.swing.JLabel();
        NewDimensionLabel = new javax.swing.JLabel();
        ValueNewDimensionLabel = new javax.swing.JLabel();
        DeriveFeatureSpaceButton = new javax.swing.JButton();
        ResoultsPanel = new javax.swing.JPanel();
        FSWinnerLabel = new javax.swing.JLabel();
        ValueFSWinnerLabel = new javax.swing.JLabel();
        FLDWinnerLabel = new javax.swing.JLabel();
        ValueFLDWinnerLabel = new javax.swing.JLabel();
        ValuesResoultsPanel = new javax.swing.JPanel();
        ClassifierPanel = new javax.swing.JPanel();
        ClassifierLabel = new javax.swing.JLabel();
        MethodLabel = new javax.swing.JLabel();
        MethodComboBox = new javax.swing.JComboBox();
        TrainButton = new javax.swing.JButton();
        ExecuteButton = new javax.swing.JButton();
        TrainingLabel = new javax.swing.JLabel();
        TrainSetSizeTextField = new javax.swing.JTextField();
        PercentLabel = new javax.swing.JLabel();
        ResultTextField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ReadDatasetButton.setText("Read dataset");
        ReadDatasetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadDatasetButtonActionPerformed(evt);
            }
        });

        ParseDatasetButton.setText("Parse dataset");
        ParseDatasetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParseDatasetButtonActionPerformed(evt);
            }
        });

        InfoPanel.setBackground(new java.awt.Color(204, 255, 255));
        InfoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        InfoLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        InfoLabel.setText("Dataset info");

        DatasetNameLabel.setText("Name:");

        ValueDatasetNameLabel.setText("...");

        ClassesLabel.setText("Classes:");

        FeaturesLabel.setText("Features:");

        ValueFeaturesLabel.setText("...");

        javax.swing.GroupLayout InfoPanelLayout = new javax.swing.GroupLayout(InfoPanel);
        InfoPanel.setLayout(InfoPanelLayout);
        InfoPanelLayout.setHorizontalGroup(
                InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(InfoPanelLayout.createSequentialGroup()
                                                .addComponent(DatasetNameLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(ValueDatasetNameLabel))
                                        .addComponent(InfoLabel))
                                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(InfoPanelLayout.createSequentialGroup()
                                                .addGap(115, 115, 115)
                                                .addComponent(ClassesLabel))
                                        .addGroup(InfoPanelLayout.createSequentialGroup()
                                                .addGap(94, 94, 94)
                                                .addComponent(FeaturesLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ValueFeaturesLabel)))
                                .addContainerGap(31, Short.MAX_VALUE))
        );
        InfoPanelLayout.setVerticalGroup(
                InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(InfoPanelLayout.createSequentialGroup()
                                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(InfoLabel)
                                        .addComponent(ClassesLabel))
                                .addGap(10, 10, 10)
                                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(DatasetNameLabel)
                                        .addComponent(FeaturesLabel)
                                        .addComponent(ValueDatasetNameLabel)
                                        .addComponent(ValueFeaturesLabel))
                                .addContainerGap(26, Short.MAX_VALUE))
        );

        FeatureSpacePanel.setBackground(new java.awt.Color(255, 255, 204));
        FeatureSpacePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        FeatureLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        FeatureLabel.setText("Feature space");

        FSDimensionLabel.setText("FS Dimension");

        FSDimensionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"1", "2", "3"}));

        CriterionLabel.setText("Criterion");

        FeatureSelectionRadioButton.setBackground(new java.awt.Color(255, 255, 204));
        FeatureSelectionRadioButton.setSelected(true);
        FeatureSelectionRadioButton.setText("Feature selection");
        FeatureSelectionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeatureSelectionRadioButtonActionPerformed(evt);
            }
        });

        FisherCriterionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Fisher discriminant", "SFS", "Classification error"}));

        FeatureExtarctionRadioButton.setBackground(new java.awt.Color(255, 255, 204));
        FeatureExtarctionRadioButton.setText("Feature extraction");
        FeatureExtarctionRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeatureExtarctionRadioButtonActionPerformed(evt);
            }
        });

        PCALDAComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"PCA", "LDA"}));
        PCALDAComboBox.setEnabled(false);

        EnergyLabel.setText("Energy");

        PCAEnergyTextField.setText("80");

        Percent2Label.setText("%");

        NewDimensionLabel.setText("New dimension:");

        ValueNewDimensionLabel.setText("...");

        DeriveFeatureSpaceButton.setText("Derive Feature Space");
        DeriveFeatureSpaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeriveFeatureSpaceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FeatureSpacePanelLayout = new javax.swing.GroupLayout(FeatureSpacePanel);
        FeatureSpacePanel.setLayout(FeatureSpacePanelLayout);
        FeatureSpacePanelLayout.setHorizontalGroup(
                FeatureSpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FeatureSpacePanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(FeatureLabel)
                                .addGap(46, 46, 46)
                                .addComponent(FSDimensionLabel)
                                .addGap(27, 27, 27)
                                .addComponent(FSDimensionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(FeatureSpacePanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(FeatureSpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(FeatureSelectionRadioButton)
                                        .addGroup(FeatureSpacePanelLayout.createSequentialGroup()
                                                .addGap(190, 190, 190)
                                                .addComponent(CriterionLabel))
                                        .addGroup(FeatureSpacePanelLayout.createSequentialGroup()
                                                .addGap(150, 150, 150)
                                                .addComponent(FisherCriterionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(FeatureSpacePanelLayout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(FeatureSpacePanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(FeatureExtarctionRadioButton)
                                .addGap(65, 65, 65)
                                .addComponent(PCALDAComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(FeatureSpacePanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(EnergyLabel)
                                .addGap(16, 16, 16)
                                .addComponent(PCAEnergyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Percent2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(NewDimensionLabel)
                                .addGap(35, 35, 35)
                                .addComponent(ValueNewDimensionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(FeatureSpacePanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(DeriveFeatureSpaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        FeatureSpacePanelLayout.setVerticalGroup(
                FeatureSpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FeatureSpacePanelLayout.createSequentialGroup()
                                .addGroup(FeatureSpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(FeatureLabel)
                                        .addGroup(FeatureSpacePanelLayout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(FSDimensionLabel))
                                        .addGroup(FeatureSpacePanelLayout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(FSDimensionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(13, 13, 13)
                                .addGroup(FeatureSpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(FeatureSpacePanelLayout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(FeatureSelectionRadioButton))
                                        .addGroup(FeatureSpacePanelLayout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(CriterionLabel))
                                        .addGroup(FeatureSpacePanelLayout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(FisherCriterionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(FeatureSpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(FeatureExtarctionRadioButton)
                                        .addComponent(PCALDAComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(FeatureSpacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(EnergyLabel)
                                        .addComponent(PCAEnergyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Percent2Label)
                                        .addComponent(NewDimensionLabel)
                                        .addComponent(ValueNewDimensionLabel))
                                .addGap(10, 10, 10)
                                .addComponent(DeriveFeatureSpaceButton))
        );

        ResoultsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Results"));

        FSWinnerLabel.setText("FS Winner:");

        ValueFSWinnerLabel.setText("xxx");

        FLDWinnerLabel.setText("FLD value: ");

        ValueFLDWinnerLabel.setText("vvv");

        javax.swing.GroupLayout ResoultsPanelLayout = new javax.swing.GroupLayout(ResoultsPanel);
        ResoultsPanel.setLayout(ResoultsPanelLayout);
        ResoultsPanelLayout.setHorizontalGroup(
                ResoultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ResoultsPanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(ResoultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(ResoultsPanelLayout.createSequentialGroup()
                                                .addComponent(FSWinnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20)
                                                .addComponent(ValueFSWinnerLabel))
                                        .addGroup(ResoultsPanelLayout.createSequentialGroup()
                                                .addComponent(FLDWinnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20)
                                                .addComponent(ValueFLDWinnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(20, Short.MAX_VALUE))
        );
        ResoultsPanelLayout.setVerticalGroup(
                ResoultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ResoultsPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(ResoultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(FSWinnerLabel)
                                        .addComponent(ValueFSWinnerLabel))
                                .addGap(16, 16, 16)
                                .addGroup(ResoultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(FLDWinnerLabel)
                                        .addComponent(ValueFLDWinnerLabel)))
        );

        ValuesResoultsPanel.setBackground(new java.awt.Color(255, 255, 255));
        ValuesResoultsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout ValuesResoultsPanelLayout = new javax.swing.GroupLayout(ValuesResoultsPanel);
        ValuesResoultsPanel.setLayout(ValuesResoultsPanelLayout);
        ValuesResoultsPanelLayout.setHorizontalGroup(
                ValuesResoultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 156, Short.MAX_VALUE)
        );
        ValuesResoultsPanelLayout.setVerticalGroup(
                ValuesResoultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 126, Short.MAX_VALUE)
        );

        ClassifierPanel.setBackground(new java.awt.Color(204, 255, 204));
        ClassifierPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ClassifierLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        ClassifierLabel.setText("Classifier");

        MethodLabel.setText("Method");

        MethodComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Nearest neighbor (NN)", "Nearest Mean (NM)", "k-Nearest Neighbor (k-NN)", "k-Nearest Mean (k-NM)"}));

        TrainButton.setText("Train");
        TrainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainButtonActionPerformed(evt);
            }
        });

        ExecuteButton.setText("Execute");
        ExecuteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecuteButtonActionPerformed2(evt);
            }
        });

        TrainingLabel.setText("Training part:");

        TrainSetSizeTextField.setText("80");

        PercentLabel.setText("%");

        ResultTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultTextFieldActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1", "3", "5", "7", "9"}));

        jLabel1.setText("K=");

        javax.swing.GroupLayout ClassifierPanelLayout = new javax.swing.GroupLayout(ClassifierPanel);
        ClassifierPanel.setLayout(ClassifierPanelLayout);
        ClassifierPanelLayout.setHorizontalGroup(
                ClassifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ClassifierPanelLayout.createSequentialGroup()
                                .addGroup(ClassifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(ClassifierPanelLayout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(ResultTextField))
                                        .addGroup(ClassifierPanelLayout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(MethodLabel)
                                                .addGap(24, 24, 24)
                                                .addComponent(MethodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(ClassifierPanelLayout.createSequentialGroup()
                                                .addGroup(ClassifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(ClassifierPanelLayout.createSequentialGroup()
                                                                .addGap(8, 8, 8)
                                                                .addComponent(ClassifierLabel))
                                                        .addGroup(ClassifierPanelLayout.createSequentialGroup()
                                                                .addGap(38, 38, 38)
                                                                .addComponent(TrainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(72, 72, 72)
                                                                .addComponent(ExecuteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(ClassifierPanelLayout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(TrainingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(10, 10, 10)
                                                                .addComponent(TrainSetSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(10, 10, 10)
                                                                .addComponent(PercentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        ClassifierPanelLayout.setVerticalGroup(
                ClassifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ClassifierPanelLayout.createSequentialGroup()
                                .addComponent(ClassifierLabel)
                                .addGap(15, 15, 15)
                                .addGroup(ClassifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(ClassifierPanelLayout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(MethodLabel))
                                        .addGroup(ClassifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(MethodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ResultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ClassifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TrainButton)
                                        .addComponent(ExecuteButton))
                                .addGap(17, 17, 17)
                                .addGroup(ClassifierPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TrainingLabel)
                                        .addComponent(TrainSetSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PercentLabel)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(ReadDatasetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(172, 172, 172))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(InfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(ParseDatasetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)))
                                                .addComponent(ResoultsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ValuesResoultsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(FeatureSpacePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addComponent(ClassifierPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(ReadDatasetButton)
                                                        .addComponent(ParseDatasetButton))
                                                .addGap(17, 17, 17)
                                                .addComponent(InfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(ResoultsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ValuesResoultsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(FeatureSpacePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(ClassifierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FeatureSelectionRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeatureSelectionRadioButtonActionPerformed
        FisherCriterionComboBox.setEnabled(true);
        FeatureExtarctionRadioButton.setSelected(false);
        PCALDAComboBox.setEnabled(false);
    }//GEN-LAST:event_FeatureSelectionRadioButtonActionPerformed

    private void FeatureExtarctionRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeatureExtarctionRadioButtonActionPerformed
        FisherCriterionComboBox.setEnabled(false);
        FeatureSelectionRadioButton.setSelected(false);
        PCALDAComboBox.setEnabled(true);
    }//GEN-LAST:event_FeatureExtarctionRadioButtonActionPerformed

    private void ReadDatasetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadDatasetButtonActionPerformed
        // reads in a text file; contents is placed into a variable of String type
        ValueDatasetNameLabel.setText(data.readDataSet(this));
    }//GEN-LAST:event_ReadDatasetButtonActionPerformed

    private void ParseDatasetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParseDatasetButtonActionPerformed
        // Analyze text inputted from a file: determine class number and labels and number
        // of features; build feature matrix: columns - samples, rows - features
        try {
            if (data.InData != null) {
                data.getDatasetParameters();
                ValueFeaturesLabel.setText(data.FeatureCount + "");
                data.fillFeatureMatrix();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_ParseDatasetButtonActionPerformed

    private void DeriveFeatureSpaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeriveFeatureSpaceButtonActionPerformed
        // derive optimal feature space
        if (data.F == null) {
            return;
        }
        if (FeatureSelectionRadioButton.isSelected()) {
            // the chosen strategy is feature selection
            int[] flags = new int[data.FeatureCount];
            int tmp = Integer.parseInt((String) FSDimensionComboBox.getSelectedItem());

            String tmp1 = (String) FisherCriterionComboBox.getSelectedItem();
            if (tmp1.equals("SFS")) {
                ValueFSWinnerLabel.setText(selection.selectFeaturesSFS(tmp, data) + "");
            } else {
                int[] a = selection.selectFeatures(tmp, data);
                String out = "";
                for (int i : a) {
                    out += i + " ";
                }
                ValueFSWinnerLabel.setText(out);
            }
        } else if (FeatureExtarctionRadioButton.isSelected()) {
            double TotEnergy = Double.parseDouble(PCAEnergyTextField.getText()) / 100.0;
            // Target dimension (if k>0) or flag for energy-based dimension (k=0)
            int k = 0;
//            double[][] FF = { {1,1}, {1,2}};
//            double[][] FF = { {-2,0,2}, {-1,0,1}};
            // F is an array of initial features, FNew is the resulting array
            double[][] FFNorm = Data.centerAroundMean(data.F);
            Matrix Cov = Data.computeCovarianceMatrix(FFNorm);
            Matrix TransformMat = Extraction.extractFeatures(Cov, TotEnergy, k);
            data.FNew = Data.projectSamples(new Matrix(FFNorm), TransformMat);
            // FNew is a matrix with samples projected to a new feature space
            ValueNewDimensionLabel.setText(data.FNew.length + "");
        }
    }//GEN-LAST:event_DeriveFeatureSpaceButtonActionPerformed

    private void TrainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainButtonActionPerformed
        if (data.FNew == null) {
            return; // no reduced feature space have been derived
        }
        String selectedItem = (String) MethodComboBox.getSelectedItem();

        switch (selectedItem) {
            case "Nearest neighbor (NN)":
                classifier = new NNClassifier(data.FNew, data.ClassLabels);
                break;
            case "Nearest Mean (NM)":
                classifier = new NMClassifier(data.FNew, data.ClassLabels);
                break;
            case "k-Nearest Neighbor (k-NN)":
                classifier = new KNNClassifier(data.FNew, data.ClassLabels, Integer.parseInt(jComboBox1.getSelectedItem().toString()));
                break;
            case "k-Nearest Mean (k-NM)":
                classifier = new KNMClassifier(data.FNew, data.ClassLabels, data.SampleCount, Integer.parseInt(jComboBox1.getSelectedItem().toString()));
                break;
        }

        classifier.generateTrainingAndTestSets(TrainSetSizeTextField.getText());
    }//GEN-LAST:event_TrainButtonActionPerformed

    private void ResultTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultTextFieldActionPerformed

    private void ExecuteButtonActionPerformed2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecuteButtonActionPerformed2
        ResultTextField.setText(Double.toString(classifier.execute()));
    }//GEN-LAST:event_ExecuteButtonActionPerformed2

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new PR_GUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClassesLabel;
    private javax.swing.JLabel ClassifierLabel;
    private javax.swing.JPanel ClassifierPanel;
    private javax.swing.JLabel CriterionLabel;
    private javax.swing.JLabel DatasetNameLabel;
    private javax.swing.JButton DeriveFeatureSpaceButton;
    private javax.swing.JLabel EnergyLabel;
    private javax.swing.JButton ExecuteButton;
    private javax.swing.JLabel FLDWinnerLabel;
    private javax.swing.JComboBox FSDimensionComboBox;
    private javax.swing.JLabel FSDimensionLabel;
    private javax.swing.JLabel FSWinnerLabel;
    private javax.swing.JRadioButton FeatureExtarctionRadioButton;
    private javax.swing.JLabel FeatureLabel;
    private javax.swing.JRadioButton FeatureSelectionRadioButton;
    private javax.swing.JPanel FeatureSpacePanel;
    private javax.swing.JLabel FeaturesLabel;
    private javax.swing.JComboBox FisherCriterionComboBox;
    private javax.swing.JLabel InfoLabel;
    private javax.swing.JPanel InfoPanel;
    private javax.swing.JComboBox MethodComboBox;
    private javax.swing.JLabel MethodLabel;
    private javax.swing.JLabel NewDimensionLabel;
    private javax.swing.JTextField PCAEnergyTextField;
    private javax.swing.JComboBox PCALDAComboBox;
    private javax.swing.JButton ParseDatasetButton;
    private javax.swing.JLabel Percent2Label;
    private javax.swing.JLabel PercentLabel;
    private javax.swing.JButton ReadDatasetButton;
    private javax.swing.JPanel ResoultsPanel;
    private javax.swing.JTextField ResultTextField;
    private javax.swing.JButton TrainButton;
    private javax.swing.JTextField TrainSetSizeTextField;
    private javax.swing.JLabel TrainingLabel;
    private javax.swing.JLabel ValueDatasetNameLabel;
    private javax.swing.JLabel ValueFLDWinnerLabel;
    private javax.swing.JLabel ValueFSWinnerLabel;
    private javax.swing.JLabel ValueFeaturesLabel;
    private javax.swing.JLabel ValueNewDimensionLabel;
    private javax.swing.JPanel ValuesResoultsPanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}